# Generated by Django 5.0 on 2024-02-15 11:43

import reviews.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(default=reviews.enums.Limits['DEF_NUM'], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(default=reviews.enums.Limits['DEF_NUM'], verbose_name='Количество'),
        ),
    ]
